train:
  epochs: 100
  batch_size: 32
  learning_rate: 0.001
  optimizer: adam
  loss: sparse_categorical_crossentropy
  early_stopping: false
  num_workers: 0
  num_folds: 5
  early_stopping_patience: 10

