model:
  name: spcnn
  run_name: 2025-07-07_15-32-10_SPCNN
  fold: 0
  device: cuda

data:
  image_size: 32
  batch_size: 1
  apply_clahe: true
  apply_dilation: true

xai:
  method: gradcam
  target_layer: features.7
  subset: all
  curated_ids: []
