model:
  name: spcnn
  run_name: 2025-07-10_10-47-13_SPCNN
  fold: 1
  device: cuda

data:
  image_size: 32
  batch_size: 1
  apply_clahe: true
  apply_dilation: true

xai:
  method: gradcam
  target_layer: feature_extractor.1.3.block.0
  subset: all
  curated_ids: [0]
  save_mode: overlay # or heatmap or raw
  normalieze_input: true
